# Generated by Django 4.2.6 on 2023-10-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_article_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_spetial',
            field=models.BooleanField(default=False, verbose_name='مقاله ویژه'),
        ),
    ]
