# Generated by Django 4.2.6 on 2023-11-15 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_ipaddress_article_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hits',
        ),
    ]
