# Generated by Django 4.2.6 on 2023-10-25 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_author',
            field=models.BooleanField(default=False, verbose_name='وضعیت نویسندگی'),
        ),
        migrations.AddField(
            model_name='user',
            name='spetial_user',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='کاربر خصوصی تا'),
        ),
    ]
